### PR TITLE
[WIP] Make use of discovered casts

### PR DESCRIPTION
**Pull request by soldag**
This PR enables reusing of discovered cast devices by the existing `cast` platform. This makes it way faster to start the playback as devices don't need to be discovered first. In case the platform has not been enabled, it falls back to doing the discovery on its own.

I also removed the sensor here as I thought it's only useful for this particular use case. If it has some other purpose, I can also revert this.

### CODE REVIEW

**Comment by fondberg** [comment]
Thanks for your PR! 
This work wss in my radar as well but I didn't because of 2 things 
1. Became father 2 days ago and have been busy
2. spotify-card (the lovelace card) needs to remove the dep for the sensor. Doing this is kind of tricky because many people use the start playback on chromecast functionality in the card and it uses the sensor. The proper fix would be to add an attribute to the cast media players so it can know if it should  initiate playback using spotcast or spotify...

**Comment by fondberg** [comment]
@soldag did you see my comment?

**Comment by soldag** [comment]
Oh, almost forgot it: Congrats for becoming father  :baby: :confetti_ball:

**Comment by fondberg** [comment]
I actually made time to add the missing functionality on home-assistant cast media player but it got closed quite quickly due to it being an architecture change
https://github.com/home-assistant/home-assistant/pull/24983

**Comment by fondberg** [comment]
closing in favor of https://github.com/fondberg/spotcast/pull/23

**Pull request closed without merging**
