### PR TITLE
Bug fix #261 for playlist_type

### LINKED ISSUE #261: After update to v3.6.19 I have Get Playlist 404
**Describe the bug**

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**
After last update  v3.6.19 new error apper 
Can't get playlist

image

Debug log
`2021-11-04 10:50:44 ERROR (SyncWorker_7) [spotipy.client] HTTP Error for GET to https://api.spotify.com/v1/views/playlists returned 404 due to Not found.
2021-11-04 10:50:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.playlists_sensor fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/views/playlists?content_limit=10&locale=en&platform=web&types=album%2Cplaylist%2Cartist%2Cshow%2Cstation&limit=10&offset=0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 98, in update
    resp = self.hass.data[DOMAIN]["controller"].get_playlists(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 293, in get_playlists
    resp = client._get(
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/views/playlists?content_limit=10&locale=en&platform=web&types=album%2Cplaylist%2Cartist%2Cshow%2Cstation&limit=10&offset=0:
 Not found., reason: None`

**Environment (please complete the following information):**
 - HA version: [ ]
 - spotcast version: [ ]

**Configuration**
Add your configuration

**Additional context**

### PR DESCRIPTION
**Pull request by gmcmicken**
See [#261](https://github.com/fondberg/spotcast/issues/261)

### CODE REVIEW

**Review by Darkfull-Dante — CHANGES_REQUESTED** [review]
git merge seems to take the "newer changes" to get_playlist currently in the main repository. Which means your changes aren't taking effect. I think you will have to sync with fondberg/spotcast and change back the method before it takes effect

**Comment by gmcmicken** [comment]
I had already done that so this could overwrite master.

**Comment by gmcmicken** [comment]
Do you want to scrap this and do the changes yourself if they were stashed?

**Comment by Darkfull-Dante** [comment]
no don't think its necessary to scrap it, I'll do the merge in a new branch and check if the changes are there, if not, i'll add them back

**Review by Darkfull-Dante — APPROVED** [review]
see comments

**Pull request merged**
