### PR TITLE
Add shuffling support

### PR DESCRIPTION
**Pull request by fondberg**

### CODE REVIEW

**Comment by fondberg** [comment]
Also add more debug logging

**Comment by fondberg** [comment]
Report from forum is that this works but not for the first song. Adding an index>1 to the play should solve it

**Comment by dannyhanes** [comment]
Looking forward to this. I have had shuffle working in the past using built in Home Assistant features, but I have never been able to have it NOT always play the first song in the playlist before shuffling.

**Comment by fondberg** [comment]
I'll see if I can squeeze some time in. Have a 4 week old baby at home so things are kind of chaotic

**Comment by dannyhanes** [comment]
@fondberg Congratulations!! My youngest just turned one. Get off the Internet and go be with your baby and spouse! All of this can wait :)

**Comment by fondberg** [comment]
closing in favor of https://github.com/fondberg/spotcast/pull/23

**Comment by fondberg** [comment]
@dannyhanes please help me test https://github.com/fondberg/spotcast/releases/tag/2.0.0.b1

**Comment by dannyhanes** [comment]
@fondberg Will do. Does this config look right? 

```
- service: spotcast.start
    data:
        entity_id: media_player.master_bedroom_speaker
        uri: 'spotify:user:username:playlist:playlist_url'
        random_song: true

**Comment by fondberg** [comment]
You cam omit shuffle if you want. It didn't work for me because it was too fast after the start of the playback and spotify shuffle apis hadn't realized something was playing. I'm tinkering with a small delay for the shuffle.

Random works though

**Comment by capstan1** [comment]
I'm getting API error with both options.
Im using Node-Red:
{
    "uri": "spotify:playlist:37i9dQZF1DX9XIFQuFvzM4",
    "random_song": "true"
}

Playback starts way faster, though! (if i dont try to use shuffle or random song)

**Comment by fondberg** [comment]
Great!

**Pull request closed without merging**
