### PR TITLE
Add: Support for HACS

### PR DESCRIPTION
**Pull request by JurajNyiri**
Adds support for [HACS](https://github.com/custom-components/hacs).

### CODE REVIEW

**Comment by JurajNyiri** [comment]
It would be also really cool to have this awesome integration featured [by default in HACS](https://custom-components.github.io/hacs/#include-default-repositories).

**Comment by fondberg** [comment]
Great stuff!

**Comment by JurajNyiri** [comment]
info.md is used for HACS in order to display information within when you click on the integration in HACS like this 
image

It is not a duplicate of readme.md as I left some unnecessary information for HACS out, like installation steps, as in HACS you just click install - but you still need to add stuff into a configuration.yaml so I left that in. I also left in general information (for people browsing through integrations), usage information (which could be moved away, or made into a simple link, so people look into GitHub for more info) and donate info. 

Please feel free to rewrite info.md as you wish or let me know and I can do the modifications.

I also looked into integrating one markdown into another one but haven't found a solution, even if possible, idk if it would work with HACS as it seems to request info.md directly.

**Comment by fondberg** [comment]
Sorry for the long feedback loop. My wife is about to give birth any day now. Let's merge this and we can see how much hustle it is yo maintain 2 information files

**Comment by JurajNyiri** [comment]
Thank you for merging and congratulations!

When you have the time, I would suggest creating a PR on HACS to add this repo by default into it, users then do not need to manually add it. Only the owner of the repo or major contributor can do so.

Steps:
https://custom-components.github.io/hacs/developer/include_default_repositories/

TL&DR: 
Just add `fondberg/spotcast` into custom_components/hacs/const.py `DEFAULT_REPOSITORIES. integration list` and create PR. 
Example:
https://github.com/custom-components/hacs/pull/64/files

**Pull request merged**
