### PR TITLE
Added options shuffle and offset

### PR DESCRIPTION
**Pull request by kleinc80**
One more, adding shuffle and offset. Formatted services.yaml for better readability.

### CODE REVIEW

**Comment by fondberg** [comment]
This is covered by the other PR right?

**Comment by kleinc80** [comment]
No, #59 and #60 are different, you can pull one or the other or both.

#61 covers everything (#59 and #60 and the Spotify Connect implementation).

**Comment by fondberg** [comment]
Merged #61 and released it as https://github.com/fondberg/spotcast/releases/tag/v2.8.0. This can be closed right?

**Comment by kleinc80** [comment]
Yes, please close!

**Pull request closed without merging**
