### PR TITLE
Quick-fix for spotify_token

### PR DESCRIPTION
**Pull request by bendikrb**
I compiled the changes proposed and authored by @AlexLadd, to fix the issue with spotify_token (#34) for now.

### CODE REVIEW

**Comment by fondberg** [comment]
Great. I'll have a look today

**Comment by fondberg** [comment]
I have now tested and have the following comments:
1. Really good job all that did all the digging!
2. This code change should really be a PR on spotify-token (https://github.com/enriquegh/spotify-webplayer-token). I can live with it being here if the credits in the comments change because right now it says the the author of the file is http://github.com/AlexLadd but the actual change is:
```
53c42
<     data = response.content.decode("utf-8")
---
>     access_token = response.cookies['wp_access_token']
55,60c44
<     xml_tree = BeautifulSoup(data, 'lxml')
<     script_node = xml_tree.find("script", id="config")
<     config = json.loads(script_node.string)
<
<     access_token = config['accessToken']
<     expiration = config['accessTokenExpirationTimestampMs']
---
>     expiration = response.cookies['wp_expiration']
65a50
```
As the commit history is gone I would like the credits for the code to reflect the actual change to the code by @enriquegh.
3. To be able to release this I need the following additions:
 - manifest.json to change the requirements to:
```
  "requirements": [
    "fondberg-spotipy==2.4.5-dev2",
    "pychromecast==4.0.1",
    "beautifulsoup4==4.8.0",
    "lxml==4.4.1"
  ],
```

**Comment by bendikrb** [comment]
>     2. This code change should really be a PR on spotify-token (https://github.com/enriquegh/spotify-webplayer-token). I can live with it being here if the credits in the comments change because right now it says the the author of the file is [http://github.com/AlexLadd](https://github.com/AlexLadd) but the actual change is:
> 
> As the commit history is gone I would like the credits for the code to reflect the actual change to the code by @enriquegh.

Yes, I agree - I just thought this may be the quickest way to get it up again quickly.
As for code credits, I haven't altered any, I left the one block at the top as-is. The change I did make, however, was to refactor the gist from @AlexLadd back in to the way it's originally structured in spotify_token (which as you pointed out, reveals the actual changes made).
Credits to the original author is in the top comment block, though, so I'm not quite sure what you mean here..?

> 3. To be able to release this I need the following additions:
> 
>     * manifest.json to change the requirements to:

OK.

**Comment by fondberg** [comment]
Hi @bendikrb I understand now. The gist https://gist.github.com/AlexLadd/db3d09b204d6c59787ad85d26c412b33 is indeed written by @AlexLadd but the confusion stems from taking a piece of that code and merging it to the spotify-token code from @enriquegh.
As the license in https://github.com/enriquegh/spotify-webplayer-token i MIT I think it is ok as a quick fix. The question is who will work to get this as a PR to  https://github.com/enriquegh/spotify-webplayer-token... Lets worry about that later...

**Comment by enriquegh** [comment]
@fondberg @bendikrb @AlexLadd thanks for looking into this!
If someone wants to shoot a PR my way, I'm happy to approve it and release a new version.

I can also give this a try today or tomorrow but can't make any promises.

**Comment by enriquegh** [comment]
v0.1.1 with this change has been released

**Pull request merged**
