### PR TITLE
Give spotify the chance to wake up devices

### PR DESCRIPTION
**Pull request by CubicrootXYZ**
Retry the spotify device list if a device is missing so spotify can wake up some devices like chromecasts.

### CODE REVIEW

**Comment by CubicrootXYZ** [comment]
This is not yet tested, just wanted to dump this idea here. I will try to test the code as soon as I have some spare time for that.

**Comment by CubicrootXYZ** [comment]
Tested it and it seems to be a fix for #170, will use it a while in my production setup and check if the devices are now always available.

**Comment by Maaxion** [comment]
This seems a little dirty solution to the problem.

`getSpotifyDeviceId()` fails because the device we want to play on, `self.spotifyController.device`, is not found in the list returned by `helpers.get_spotify_devices()`.

That function in turn seems to [call `devices()`](https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/helpers.py#L48) from `spotipy` [directly via the spotify media player object](https://github.com/home-assistant/core/blob/dev/homeassistant/components/spotify/__init__.py#L124).

[Spotipy's `devices()`](https://github.com/plamere/spotipy/blob/master/spotipy/client.py#L1700) does an API call to spotify to request your available devices.

This seems to imply that spotify itself is not yet aware that the chromecast has booted with spotify active when we are initiating the play request.

What we basically need to do is 1) ensure that the chromecast devices we want to play on is started and then 2) wait until it is discovered by spotify

I think a better solution would be to refactor `getSpotifyDeviceId` and `get_spotify_devices` such that we would have a method that checks periodically for the chromecast device we are trying to play on to appear in spotifys list of known devices, and to only fail after a specific timeout (30 seconds? a minute?).

This would be a more robust solution to the problem that wouldn't fail in case it takes longer than ~2s for the chromecast device to be discovered by spotify and would also make it cleared from the code as to what is going on.

@hmmbob or @fcusson, what do you think of this proposed alternate solution? If you feel it would be OK, I could create a PR.

**Comment by Maaxion** [comment]
I created an alternative PR with a different fix: https://github.com/fondberg/spotcast/pull/339

**Comment by fcusson** [comment]
better implementation in #339, will close this merge request. still a good first draft

**Pull request closed without merging**
