### PR TITLE
Use core constants and sort imports

### PR DESCRIPTION
**Pull request by yuvalabou**
Tested and working locally

### CODE REVIEW

**Comment by fondberg** [comment]
Nice cleanup. Did you use black?

**Comment by yuvalabou** [comment]
Yes, why?

**Comment by fondberg** [comment]
no reason. It is good. I need to see why some constants are not used anymore. Think it might be a faulty PR some time ago

**Comment by hmmbob** [comment]
They're not removed, they're now imported from HA Core.

https://github.com/fondberg/spotcast/pull/205/files#diff-fe5324fc17fd5cbefbe7a32bb34458ea6de7edfb06e87e23b12c47056126f5ceR17

**Review by fondberg — APPROVED** [review]

**Pull request merged**
