### PR TITLE
Add hassfest test

### PR DESCRIPTION
**Pull request by yuvalabou**
Validate with hassfest

### CODE REVIEW

**Comment by fondberg** [comment]
1. What does this validate?
2. Have you tried validation offline to see how much fails?

**Comment by hmmbob** [comment]
https://developers.home-assistant.io/blog/2020/04/16/hassfest/

**Comment by yuvalabou** [comment]
> 2. Have you tried validation offline to see how much fails?

Yes, however it fails on current version since we are calling 'http' lib and it does not included in the requirements. I can rebase now since you have merged my previous PR which removes the http inclusion.

**Comment by fondberg** [comment]
Great, lemme know when you have done that so I can merge

**Comment by yuvalabou** [comment]
It's done, just that file

**Comment by yuvalabou** [comment]
Done

**Review by fondberg — APPROVED** [review]

**Comment by fondberg** [comment]
Question, if we remove homeassistant version from the manifest we loose the possibility to enforce a version. Is there a way to keep it?

**Comment by hmmbob** [comment]
I think it's not allowed in manifest.json, but it is a parameter in HACS.json

**Comment by fondberg** [comment]
I see. Used to work in manifest.json. weird that it is removed

**Pull request merged**
